//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossChat.Domain.DBModel
{
    
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Text.Json.Serialization;

    public partial class Channel : BaseEntity
    {
        [Required(ErrorMessage = "Please choose Channel Name")]
        [StringLength(30, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 3)]
        [DataType(DataType.Text)]
        [Display(Name = "Channel Name")]
        public string ChannelName { get; set; }
        
  

        public string Description { get; set; }


        [Required]
        [Display(Name = "Avatar")]
        public string Avatar { get; set; }

        public bool IsReadOnly { get; set; } = false;

        [JsonIgnore]
        public List<MemberShip> MemberShips { get; set; }
        [JsonIgnore]
        public List<Message> Messages { get; set; }

    }
}
