//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossChat.Domain.DBModel
{

    using System.Text.Json.Serialization;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System;

    public partial class MemberShip : BaseEntity
    {
        [Required]
       [ForeignKey("Channel")]
        public Guid ChannelId { get; set; }
        [Required]
        [ForeignKey("User")]
        public Guid UserId { get; set; }
        
        public bool isCreator { get; set; }

        public Channel Channel { get; set; }
        public User User { get; set; }
        
    }
}
